### ISSUE TITLE
Strange chord in Purcell Z807

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#12]
I finally traced down the chord that behaves strangely in my code. It is the `V63b3` in `m212`, nearly at the end of Purcell's Z807:

```
m207 b1 v6
m208 b1 VI b3 iv6
m209 b1 v b2.5 v42 b3 III7
m210 b1 IV b2 v
m211 b1 #viø65 b2 c: III+6 b3 i64
m212 b1 g: It6 b2 V63b3
m213 b1 iiø43
m214 b1 V b2.5 V642 b3 i6
m215 b1 iv9 b2 v7
m216 b1 iiø42 b2 i
m217 b1 i42 b2 bVII[add2]
m218 b1 iiø43 b2 viio42
m219 b1 V b2.5 viio64 b3 i6
m220 b1 iv7 b2 V
m221 b1 i
```

On IMSLP, I could only find a 2-keyboard arrangement, looking like this for mm.211-213:
![image](https://user-images.githubusercontent.com/7258463/103423918-9d77d600-4b77-11eb-8e68-74b33cf8103b.png)

EDIT: Sorry about the lack of clefs: here is the full line:

![image](https://user-images.githubusercontent.com/7258463/103424118-930a0c00-4b78-11eb-90b0-0dcea95735d1.png)

Not easy to make a judgement from that score about the Italian or the dominant in mm.212!

Maybe `v6` instead of `V63b3`?

**Comment by napulen** [comment]
By the way, this is interpreted in `RomanNumeral` as:

```python
In [3]: c = RomanNumeral("V63b3", "g")                                                                                                                                                                             

In [4]: c                                                                                                                                                                                                          
Out[4]: <music21.roman.RomanNumeral V63b3 in g minor>

In [5]: c.pitchNames                                                                                                                                                                                               
Out[5]: ['F#', 'A', 'A', 'D']

In [6]: c.pitches                                                                                                                                                                                                  
Out[6]: 
(<music21.pitch.Pitch F#5>,
 <music21.pitch.Pitch A5>,
 <music21.pitch.Pitch A5>,
 <music21.pitch.Pitch D6>)
```
It is a triad (i.e., `c.isTriad() == True`), so it forces the algorithm to double one of the notes AND arrange for an additional `A` too, hence all the mayhem :).

**Comment by MarkGotham** [comment]
Thanks for this. Yes, that's definitely now what we want(!), and v6 (F nat.) makes the stronger case here (than F#). This will have crept in from issues with romanNumeralFromChord that are hopefully outdated now given all the great, recent work on that corner of music21.

**Comment by MarkGotham** [comment]
(p.s. there's a score in this repo)

**Comment by napulen** [comment]
Oops! I forgot about the score in the repo! Sorry about that.

Thank you for the commit w/correction!
