### ISSUE TITLE
op28 (bps_15_01)

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#14]
Assuming that the scores at the `functional-harmony` repository are the accompanying score to the analyses of Beethoven Op.28, there is something weird happening when aligning the score with the annotation file.

Issue happens around mm.163a:

![image](https://user-images.githubusercontent.com/7258463/107731456-09477580-6cc4-11eb-92ce-c7c4c8de8965.png)

It seems that the `I` annotation at mm.167 (highlighted) should appear in mm.168 instead. This triggers a misalignment of the scores starting from this measure.

It is very tricky because there is that repetition bar (indicated in the analysis as `163a`, and I assume `163b` on the other side), which spans two measures on the right side of the repetition bar.

Not sure whether it is an error in the MusicXML file, or maybe the annotations should change the measure numbers?

(I'll be inspecting the BPS score-annotation alignment more in depth for the following days)

**Comment by MarkGotham** [comment]
Thanks for this @napulen!
 
In the general case, I don't think we can / should offer to guarantee alignment with external scores ...

... but in this specific case there's an easy and obviously desirable fix that provides that alignment: 

For 1st/2nd time repeat measures we need to include both, even if that means explicitly repeating an ongoing chord.

Thanks again for flagging it up.
