### ISSUE TITLE
Omitted annotation in first measures of Monteverdi madrigals

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#26]
Several Monteverdi madrigals display the following pattern:

![image](https://user-images.githubusercontent.com/7258463/111071299-e7503700-84ab-11eb-892c-146db9a58510.png)

The first measures have some weird/chromatic/ambiguous/monophonic/etc. content, and thus have been omitted from the annotation.

```
Composer: Claudio Monteverdi
Madrigal: 4.20
Title: Piagn'e sospira: E quand'i caldi raggi
Time Signature: 4/4
Key Signature:

Note: Very chromatic music; key is hard to determine
Note: m1-4 single voice, m5-6 two voice texture
m5 g: III
m6 viio6
m7 i
m8 V/ii
m9 ii b3 VII
m10 V/v
m11 v6 b2 v b3 III6
m12 VII b3 ii[no3]
m13 I
m14 IV
m15 ii b3 v
```

The problem is that note `offsets` will never align because the annotation file will start on `m5` with offset `0.0` while the score will have a different offset for `m5`.

A number of things can be done for this:
1. Add "dummy" annotations of all measures in the RomanText, to mimic the original structure of the piece, although the annotations will be ambiguous/incorrect
2. Whenever the first measure in the RomanText != `m0` or `m1`. Insert blank measures with no annotations just to preserve the proper offset once the annotations tart
3. Remove the first measures from the score, and start right from the place where the annotations start. Add a text note somewhere in the score about measures removed and why they were removed (e.g., as an Ossia image or similar)

I don't like (2) because there are too many things that can go wrong (e.g., what happens if the beginning is a recitativo with a very weird time signature; you won't be able to know that or infer how many `quarterLength` values have happened before your annotations start). I incline for (1) or maybe (3).

No idea which one is the best compromise, hence, the issue.

**Comment by napulen** [comment]
By the way, potential files that feature this same problem:

```
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_4/20/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_4/1/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_3/7/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_3/20/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_3/5/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_3/4/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_5/3/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_4/18/score.mxl
When-in-Rome/Corpus/Early_Choral/Monteverdi,_Claudio/Madrigals_Book_4/6/score.mxl
```

I haven't confirmed that misalignment is related to this in all cases, but it is likely. The example I shared is the first one on the list.

**Comment by napulen** [comment]
Relevant for (3): https://musescore.org/en/node/46226

**Comment by MarkGotham** [comment]
Hey @napulen . Sorry for the delay on this! Now solved with updated scores and analyses from DT. It looks like everything works well now except for 2 remaining alignment issues to investigate:
- Book 5 # 06
- Book 3 # 11
