### ISSUE TITLE
Trailing beat information on ABC annotation file

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#30]
https://github.com/MarkGotham/When-in-Rome/blob/4f9ed6eb0d42daa6b92d21f1e16b10f25e27c20a/Corpus/Quartets/Beethoven%2C_Ludwig_van/Op18_No1/1/analysis.txt#L64

I stumbled upon this trailing beat. It seems to trigger weird partial measures on the annotation stream

![image](https://user-images.githubusercontent.com/7258463/112529017-31be9700-8d7b-11eb-91cb-3fdabcfe3760.png)

I am not sure if this is the only issue like this on ABC, but I suspect not.

Bringing this one up, while I am chasing other similar ones.

**Comment by MarkGotham** [comment]
Is this all sorted now? Ready to close?

**Comment by napulen** [comment]
Yes!
