### ISSUE TITLE
Typo in analysis

### ISSUE THREAD

**Issue by malcolmsailor** [MarkGotham/When-in-Rome#39]
In the analysis of the following piece:

> Composer: Franz Schubert
> Title: Winterreise, D.911 - 18: Der stürmische Morgen

In the following line, 

> m13 V42/IV b1.5 IV6 b2 iioø43 b2.5 iii6 b3 I

iioø43 should presumably be iiø43.

![Screen Shot 2022-03-16 at 9 24 34 AM](https://user-images.githubusercontent.com/28103673/158599837-f975e621-51be-4f58-8e2f-403c453d74f3.png)

(Sorry I am not submitting a pull request but I think it will be easier for you to delete the excess character than for me to create a fork for this purpose.)

**Comment by malcolmsailor** [comment]
Another one:

> Composer: Monteverdi
> Madrigal: 4.2
> Title: Cor mio, mentre vi miro

In this line

> m44 VII b3 viio6/iv6 b4 iv6

We should presumably drop the last character of "viio6/iv6".

M

**Comment by MarkGotham** [comment]
Thanks @malcolmsailor and no worries. I (and DT) have fixed these in the latest commits.

We should take this observation back to music21. E.g.:
" The rntxt syntax generously accepts a few dodgy bits of syntax:
- `oø` (should pick one or the other!)
- `V/V6` (i.e. with meaningless inversion on the secondary key)

Should we print a warning to the log? Personally I prefer that tor throwing the whole analysis out. "
