### ISSUE TITLE
Observations on local keys: annotation decisions or parsing error?

### ISSUE THREAD

**Issue by jonnybluesman** [MarkGotham/When-in-Rome#44]
Hi everyone, we are currently evaluating a system built on your corpus, and a potential inconsistency was brought up by the musicologists involved in our study. It concerns the annotation of local keys in the score, and in particular, it was spotted for Schubert's Das Wandern in the `OpenScore-LiederCorpus` subset.

From the analysis on the score (`analysis_on_score.mxl`), at measure 15, an `f` letter is used before the Roman numeral (see the screenshot below).
<img width="964" alt="Screenshot 2022-08-11 at 13 59 35" src="https://user-images.githubusercontent.com/13005049/184141260-4873b89a-451a-461b-b3b6-3d08b8199763.png">

When reading this with `music21`, the letter is interpreted as `F minor` (see the snippet below).

```python
import music21

romantext_sample = "OpenScore-LiederCorpus/Schubert,_Franz/Die_schöne_Müllerin,_D.795/01_Das_Wandern/analysis.txt"

m21_score = music21.converter.parse(
    romantext_sample, format='romanText')

numerals = [(numeral.getContextByClass('Measure').measureNumber, numeral) \
            for numeral in m21_score.recurse().getElementsByClass('RomanNumeral')]

numerals[20:]
```

Which produces the following output (an excerpt is reported here).
```
...
(14, <music21.roman.RomanNumeral i in g minor>),
 (15, <music21.roman.RomanNumeral I6[no1] in f minor>),
 (15, <music21.roman.RomanNumeral V65[no3] in f minor>),
 (15, <music21.roman.RomanNumeral I in f minor>),
 (15, <music21.roman.RomanNumeral V6 in f minor>),
...
```

However, our musicologists observed that the annotation would be incorrect if interpreted in this way. In particular, _the annotator that performed the Roman numeral analysis has potentially used `f` instead of `F` to indicate the brief moment in which `F` is tonicized_; and that _it is unlikely that it is `F minor` as there are no `Ab`s_.

Therefore, should we consider the output of the `music21` parser correct (meaning that, `f` is actually F minor), and interpret this as an annotation decision? Or could this be a bug (or a "corner case") of the parser? Thanks a lot for your time.

**Comment by MarkGotham** [comment]
Yup, that's definitely a typo in the analysis. In so far as this should be it's own key area, it's definitely `F` and not `f`.

Thanks for the catch. Feel free to PR fixes on clear errors like this.

**Comment by MarkGotham** [comment]
Stay tuned for a full update soon. And let me know if you have any design preferences to consider. Thanks!
