### ISSUE TITLE
Reger ex 20

### ISSUE THREAD

**Issue by malcolmsailor** [MarkGotham/When-in-Rome#46]
`Corpus/Textbooks/Reger,_Max/Modulation/20/score.mxl` seems to be an empty musescore file.

![Screen Shot 2022-08-16 at 10 34 31 AM](https://user-images.githubusercontent.com/28103673/184932098-6cd09289-cbb2-47bf-a334-6ce92f4321d7.png)

Ditto for `Corpus/Textbooks/Reger,_Max/Modulation/41/score.mxl`

@napulen, is there a repository specifically for the Textbook examples I should post this issue to?

**Comment by MarkGotham** [comment]
Thanks @malcolmsailor. This is the source repo: https://github.com/DDMAL/key_modulation_dataset.

@napulen, let us know how you want to proceed (i.e., changes directly here or at source and re-converted)

**Comment by napulen** [comment]
Uhm... Looking into this now.

**Comment by napulen** [comment]
The original does have a score, so that means the translation failed. I'll retranslate and send a revision.

**Comment by MarkGotham** [comment]
Hey @napulen

Little nudge on this ;)

**Comment by napulen** [comment]
See #79
