### ISSUE TITLE
Clean-up for consistent dir contents

### ISSUE THREAD

**Issue by MarkGotham** [MarkGotham/When-in-Rome#48]
Dear @napulen, @malcolmsailor, all,

As we gradually move towards a first coherent form and release of this dataset, it's time for a cleanup to make the contents of each directory as consistent as possible.

I'm inclined to think that less is more, so would suggest we include in each folder only the minimum:
- `score.mxl`
- `analysis.txt`
- (Optionally) `Working/` for clarity on conversion processes.

All of the additional files like ...
- `slices`
- `profiles`
- etc.

... are easy to generate anew with code and instructions provided, but not included by default. There are now a lot of different variants (see the `Code/Example` folder for all supported). As always, I welcome counter suggestions and requests. Speak now!

**Comment by napulen** [comment]
> I'm inclined to think that less is more

Agree!

1. What is the precise meaning of `Working/`?
2. What about the `analysis_automatic.txt`. Would that be in a separate place? Just mentioning this because the recent PR put them on the root of each folder

**Comment by MarkGotham** [comment]
Thanks @napulen . Yes, true, let's keep `analysis_automatic.txt` in there too.

`Working/` folders show intermediary steps in converted corpora. For example, see `Working/BPS_in_transit.csv` for the BPS conversions of the Beethoven sonatas. 

Have a look at README (updated just now) and see what you think. If you approve then I'll implement that set of deletions (i.e., turn this description from aspiration into reality and put my money where my mouth is!).

Thanks!

**Comment by MarkGotham** [comment]
Done
