### ISSUE TITLE
Monteverdi score correction (where should .mxl corrections go?)

### ISSUE THREAD

**Issue by malcolmsailor** [MarkGotham/When-in-Rome#49]
I noticed an error in Monteverdi Book 5, no 4: the highlighted E-flat should be followed by another E-flat (and tied to it, in the case of the upper of the two voices, which has a dangling tie), not by E-natural.

![Screen Shot 2022-09-15 at 6 56 01 AM](https://user-images.githubusercontent.com/28103673/190386625-f6b23105-a934-4dc3-9572-d0069c1b4447.png)

This inspires a meta-question: where should such corrections go? Should I submit them to this repository or elsewhere and then we will merge them in from there?

Also what is the best way of creating .mxl files? In this case I think the easiest might be to unzip it, edit the .xml as plain text, then rezip it.

**Comment by MarkGotham** [comment]
Thanks @malcolmsailor. Yes to the error, yes please to fixing, and yes also to the method!

As for upstream corrections, yes we should propose corrections to the source where possible though it's complex in this case: these scores are DT's updates from the music21 set. I'll let him know of the issue and ask if he has a preferred reporting method.

**Comment by MarkGotham** [comment]
Hi @malcolmsailor .

As you may have seen, I've started using remote paths to scores, especially those hosted elsewhere and that music21 can parse. See:
- the `remote.json` files
- the script for parsing scores directly from URLs

That includes the m21 set of Monteverdi madrigals, so let's propose changes to that corpus there. And if DT releases his edits somewhere else then we can point to them.

That's the only m21 contribution btw: I have a new repo for the Bach chorales.
