### ISSUE TITLE
URL column in tsv files

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#51]
It seems that the [OpenScore](https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/OpenScore-LiederCorpus_contents.tsv) list includes a `URL` column, but none of the other `tsv` files has this column.

Would it be worth it to have an empty `URL` on all other `tsv`s, just for consistency? No strong preference here. It could be that this one has that unique column

**Comment by MarkGotham** [comment]
Better as it is, I think. Only open score provides corpus-wide, web-viewable scores.
