### ISSUE TITLE
`COLLECTION` not always populated in `tsv` files

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#52]
For example, the https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/Variations_and_Grounds_contents.tsv has a mostly empty `COLLECTION` column, while some or most of these rows seem to belong to a collection.

**Comment by MarkGotham** [comment]
Thanks @napulen . This is missing by design as most of these scores are stand-alone. E.g.,
- Relevant when there's one movement from the B minor mass (i.e. a 'collection'),
- but not for Beethoven Op34

Open to alternative suggestions.
