### ISSUE TITLE
"Slices" tsv, when should it exist?

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#53]
It seems in some files with scores (e.g., `Boulton,_Harold` from the 19th century songs) there is no `slices.tsv`, whereas in others there is. I thought the rationale for `slices.tsv` would be that it can be an alternative to working with the score.

I also remember discussions about removing `slices.tsv` entirely. Maybe this is a good time to decide what exactly should happen regarding slices and commit to that decision?

**Comment by MarkGotham** [comment]
Thanks. As discussed in #48 and now implemented.
