### ISSUE TITLE
Introduce github actions and improve tests

### ISSUE THREAD

**Issue by giamic** [MarkGotham/When-in-Rome#55]
When I started working with the repo I had some failing tests. Those were probably due to path issues but I could not verify that the tests were actually supposed to pass because github is not running them.

I propose to do the following:
- put all the tests in a separate folder, as it is more commonly done. See for instance https://github.com/napulen/AugmentedNet or https://github.com/huggingface/transformers
- introduce a github action to run all tests regularly, for example before every PR is merged in

**Comment by MarkGotham** [comment]
Definitely all good suggestions for moving this forward – yes please!
