### ISSUE TITLE
Remote paths for scores

### ISSUE THREAD

**Issue by MarkGotham** [MarkGotham/When-in-Rome#65]
Support option for parsing score from remote path.
Reasons:
- avoid duplicating files (complex and rights issue);
- flexible wrt changes to those scores (e.g., external corpus update);
- flexible changing which score to use (e.g., new corpus);
- shrinks meta-corpus to fraction of the size.

**Comment by MarkGotham** [comment]
Store suggested remote path in `score.txt`
- if not `score.mxl`
- open `score.txt`
- load remote path stored there
Potentially also suggestions for known alignment issues e.g., remove 1st time bars from both.

**Comment by MarkGotham** [comment]
Apply immediately as solution to missing scores for Beethoven Piano Sonatas.
Later, consider expanding to other corpora.

**Comment by MarkGotham** [comment]
Where a local `score.mxl` files exists, perhaps still include the `score.txt` for source information (i.e., again, URL pointing to the source, and possibly more info).

**Comment by MarkGotham** [comment]
Remote sores would mean tinkering with the music21 environment settings.
Here's a draft that gets the job done but also leaves the place as we found it.
Anyone (e.g., @jacobtylerwalls) more familiar with this and spot any issues?
```
urlPath = 'https://raw.githubusercontent.com/user/repo/file.mxl'
autoDownloadSettingAtStart = environment.Environment()['autoDownload']  # Get current setting
environment.set('autoDownload', 'allow')  # Change current setting
score = converter.parse(urlPath)  # And do anything with it
environment.set('autoDownload', autoDownloadSettingAtStart)  # Restore settings as they were
```

**Comment by jacobtylerwalls** [comment]
I think the documented interface is the `UserSettings` class, but I don't know why, exactly.

**Comment by giamic** [comment]
Or, we might use `curl` for download a local copy of the score and store it in the folder with the "score.mxl" name. The advantage is that we do it only once; the disadvantage is that we don't automatically get updates from the original repo.

**Comment by MarkGotham** [comment]
Thanks both.

I guess I'm mostly thinking that it's unwise to tinker with users' environment settings, especially as that functionality would probably be tucked deeply into other functions. We can alert with warnings and the like, of course, but still ...

@giamic, does `curl` address that concern?

Perhaps it's best to leave it with the music21 error message, or one of our own like "To use this function you need to set your environment settings" (with how to instructions).

**Comment by MarkGotham** [comment]
Reminded myself that I've considered this for musescore files before:
https://github.com/MarkGotham/When-in-Rome/blob/97e91852e00b5bcbdf1bd88d00a111d6141e284f/Code/updates_and_checks.py#L299-L303

**Comment by MarkGotham** [comment]
> Apply immediately as solution to missing scores for Beethoven Piano Sonatas.
> Later, consider expanding to other corpora.

So, again this ^.

**Comment by giamic** [comment]
Curl is just a way to download the file locally. Once that is done, no other changes are needed. So basically we bypass the problem of remote scores on m21

**Comment by MarkGotham** [comment]
Which version of the Beethoven sonatas? Perhaps [this one](https://github.com/craigsapp/beethoven-piano-sonatas/) from @craigsapp?

Am I right in thinking:
1. @napulen, this is what you used in Augmentednet?
2. @craigsapp, you approved that use in Augmentednet? You and @napulen discussed this then as I recall but I don't see a licence on the repo.

Further questions for @craigsapp
- assuming 2. above, are you content with something similar here: i.e., pointing to your score repo as an external source, not hosting anything here.
- Do you have a preference between curl (downloading a copy for users locally on their machine) and downloading only from url at run time with music21?

Thanks all. Grateful for your views and aiming not to step on any toes!

**Comment by napulen** [comment]
Just to clarify on 1. I ended up using the scores by user *ClassicMan* (which should be the ones available in other MIR repositories?)

I was originally intending to use the ones by @craigsapp but, after running a [note-by-note comparison](https://napulen.github.io/beethoven_piano_sonatas_comparison/), I noticed that the transcriptions used for the BPS dataset were probably closer to the scores by ClassicMan, so it lead to a lower risk of misalignment to use those scores.

**Comment by MarkGotham** [comment]
> Just to clarify on 1. I ended up using the scores by user _ClassicMan_ (which should be the ones available in other MIR repositories?)

Thanks @napulen. Can you clarify where and what the licence is?

**Comment by napulen** [comment]
These are all files without an explicit license (assumed all rights reserved). I reached out to the author privately and received permission to use them for training the network.

**Comment by MarkGotham** [comment]
Thanks all.

FYI @giamic , @napulen, this is now done for krn scores:
- Beethoven piano sonatas and 
- TAVERN dataset

Not for:
- MuseScore (added explanation to readme)
- Haydn Op20 and others for which new scores are coming v soon.

Feedback (always) welcome. Thanks again.
