### ISSUE TITLE
"Exception: Too many notes" on parsing some analyses

### ISSUE THREAD

**Issue by giamic** [MarkGotham/When-in-Rome#68]
Some analyses fail to parse giving the following error:
```
music21.romanText.translate.RomanTextTranslateException: too many notes in this measure: m24 V V b1.5 VI b1.5 VI b2 iio6 b2 iio6 b2.5 V b2.5 V b3 i b3 i b4 Eb: V6/ii b4.5 c: V/iv
```
This happens for example in Mozart sonatas: `K570/2`, `K283/2`, `K331/1`.

**Comment by MarkGotham** [comment]
Cadenza?

**Comment by giamic** [comment]
Probably. But those are correct annotations and we should be able to parse them properly

**Comment by MarkGotham** [comment]
No cancel that. It's not the #40 issue but rather #58.
