### ISSUE TITLE
Remove all `5(4)` style syntax from AugmentedNet output automatic analyses

### ISSUE THREAD

**Issue by MarkGotham** [MarkGotham/When-in-Rome#76]
- Not in the syntax.
- Medium priority.
- @napulen

**Comment by napulen** [comment]
This is confusing. The `5(4)` notation doesn't exist in the vocabulary of the AugmentedNet model. Do you have any example automatic analysis that you can point me to?

**Comment by MarkGotham** [comment]
Mea maxima culpa!

I was sure I had found examples of this in the automatic analyses, but now I can't find any. I wonder what I was looking at! 

Note to self:
- always provide the example at the point of raising the issue.
- investigate further.

Sincere apologies!

**Comment by napulen** [comment]
No worries at all! I was fearing a batch `cp` command going catastrophically wrong in my pull request, so this is good news :).
