### ISSUE TITLE
Fix testRomanUmpire

### ISSUE THREAD

**Issue by giamic** [MarkGotham/When-in-Rome#78]
The test on the roman umpire fails. There are two issues:
- analysisOnScore.mxl can't be parsed
- the output of the umpire is not the same for all alternatives (separate score and analysis, slices and analysis, and analysis on score — which anyways can't be parsed yet)

**Comment by MarkGotham** [comment]
Thanks @giamic. 

Done with 6ad86acfe95d3e0922ac021673d9fafdc601f542
