### ISSUE TITLE
Improved metadata

### ISSUE THREAD

**Issue by johentsch** [MarkGotham/When-in-Rome#83]
https://github.com/MarkGotham/When-in-Rome/blob/30b3240d8ac58b72b417cbd37523b40486e9606b/Corpus/Keyboard_Other/Tchaikovsky%2C_Pyotr/Seasons%2C_Op.37a/7/analysis.txt#L1-L4

Could we please ask to clearly identify the origin of the DCML analyses? As a quick fix, it would be OK for groups of files to point to their respective corpus repositories (not the DCMLab organization), or, even better because sustainable, their DOIs. Ideally, the names of annotators and reviewers would figure, too, but a small mention of our metadata or a small nod to "the collaborators of the DCML" or something along those lines would already be warmly welcomed.

On the more general side, and something where I lag behind my own expectations myself, I would love to see commit hashes that identify for each converted file the version of the code used to produce it as well as the version of the original data. Apart from that, it is currently not straightforward to trace back the files to the originals, consider for example the relative paths `Corpus/Keyboard_Other/Tchaikovsky,_Pyotr/Seasons,_Op.37a/7/analysis.txt <-> tchaikovsky_seasons/harmonies/op37a07.tsv`. In combination, hashes, version numbers and links to the source (code) files would represent a splendid boon for data traceability and open science.

**Comment by MarkGotham** [comment]
Hi @johentsch.

Thanks for your input – I appreciate the second pair of eyes on this especially as this gets set up. I've been preparing you an email but am happy to talk here instead.

## Philosophy first

As you know -- but I'll reiterate (at the risk of virtue signalling) for the benefit or anyone following ;) -- I emphatically fly the flag for openness etc. a vigorously as anyone.

## Context / Open to change

I'm happy to implement any additional specific changes that are sensible and maintainable.

By way of evidence: The only request I'd received before was Martin mentioning in person that he'd like the licence on each file. Duly delivered (as you’ve seen) in this line in the code base:
https://github.com/MarkGotham/When-in-Rome/blob/cb7cced1ee5963a44afbc847fd232e643154c2d2/Code/collect_convert.py#L348

It sounds like DCML would now like that line to **include the url to the commit-specific source**?

That's also no problem: as you'll see in context, thanks to a recent refactor, that line in the code can easily retrieve the commit-specific url from the accompanying `remote.json` file (see below).

Basically, I'll gladly write whatever you like in there (with a slightly preference for brevity where possible!). Feel free to let me know exactly what you want and (within reason!) I'll implement it meta-corpus-wide right away. Perhaps something like:

Template:
```
analysis.metadata.analyst = f"DCMLab members and contributors. Licence CC-BY-NC-SA. This file is automatically converted from {url}. Please refer to that source repository for full details."
```
... where the `url` includes the specific commit.

Result:
```
Analyst: DCMLab members and contributors. Licence CC-BY-NC-SA. This file is automatically converted from https://raw.githubusercontent.com/DCMLab/tchaikovsky_seasons/8794c63afae7cd3a7f3299c57bd326ae5b681b65/harmonies/op37a07.tsv. Please refer to that source repository for full details."
```

Additionally / alternatively, the `.txt` analysis file could also simply mention / point to the presence of the accompanying `.json` file for more information. That'd also be easy to do for every case.

## Out of scope

Much as I appreciate all analysts' work, explicitly identifying every one of the DCML contributors on each file here is not wise IMO (not maintainable or desirable). DCML might add new layers or reviewers at any time (and should feel free and encouraged to do so!). If you see an easy way to include this then please by all means pitch in a PR or make a suggestion, but I'd think it's much better practice to:
- have the VoR information stored in one place (your source repo) and
- refer to that source from from here.

## Metadata in each dir's `remote.json`

Speaking of all this, have you seen the new `remote.json` files that accompany each of these? I've introduced them exactly to provide this kind of richer metadata including a link to the commit.

E.g., in the dir of the file you mention:
https://github.com/MarkGotham/When-in-Rome/blob/30b3240d8ac58b72b417cbd37523b40486e9606b/Corpus/Keyboard_Other/Tchaikovsky%2C_Pyotr/Seasons%2C_Op.37a/7/remote.json#L5

This is extremely good for traceability, right? It scores on that metric with the detraction being that it's currently only semi-automated. I manually store the commit code on [this central metadata file](https://github.com/MarkGotham/When-in-Rome/blob/master/Code/Resources/metadata.py) and write the url with it to the json at the point of conversion. 

Given that, adding this information to the `.txt` file means duplication (-1), but at least that part can be generated from a single source automatically if using the line I mentioned above (+1). I’m inclined to view this also as a +1 for the recent refactor.

Those json files also help keep track on the complex triangulating between your repos and other source. The Beethoven sonatas are a case in point: 3x overlapping, partial sets of analyses + 2x sets of scores. Difficult to coordinate, but exciting prospects for comparative analysis!

**Comment by MarkGotham** [comment]
Ok this is getting too long.

In short, I'll replace the line I mentioned with ...

`analysis.metadata.analyst = f"DCMLab members and contributors. Licence CC-BY-NC-SA. This file is automatically converted from {url}. Please refer to that source repository for full details."`

... or some variant of your choosing.

Yes?

**Comment by MarkGotham** [comment]
p.s.
In tandem with the `remote.json` links, I've stopped duplicating the tsv files from DCML repos. This too serves to keep the VoR in one place (yours) that can update freely etc. without loss of transparency wrt sources. I trust that sounds good. In any case I'm always open to suggestions / requests.

**Comment by johentsch** [comment]
Thanks, @MarkGotham, I had not seen the commit-specific links in the JSON files, this is indeed looking fantastic! Under this light, for the sake of brevity, 

> DCML members and contributors. Licence CC-BY-NC-SA. This file is automatically converted from 
> https://github.com/DCMLab/tchaikovsky_seasons. Please refer to that source repository for full details.

as I see it would be doing full justice. Or some variation on the second line referring to 
* DOI 10.5281/zenodo.7473586 (who knows who will buy GitHub one day) or
* DCMLab/tchaikovsky_seasons/commit/5d62c3c or 
* DCMLab/tchaikovsky_seasons/tree/v1.1 and/or
* the `remote.json` file. 

I understand and agree that it needs to remain maintainable and within reason, and think you've found a great way of minimizing data duplication!

**Comment by MarkGotham** [comment]
Terrific! Nice doing business with you!
Here goes:
941ec9b39e756c6ae8c83cdd48e771ef34f9683b
